server:
  port: 8761
eureka:
  renewalPercentThreshold: 0.85
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: eureka-service