spring:
  application:
    name: song-resource-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://song-resource-service-db:3306/song_resource_database
    username: root
    password: pass123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      defer-datasource-initialization: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
