spring:
  application:
    name: song-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://song-service-database:3306song_database
    url: jdbc:mysql://localhost:3308/song_database
    username: root
    password: pass123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      defer-datasource-initialization: true
    show-sql: true
server:
  port: 8092
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka